### ISSUE TITLE
Stats+ Repentogon Issue

### ISSUE THREAD

**Issue by LlamaLord23** [aleksander-ciesielski/isaac-stats-plus#10] opened 2024-03-03 04:23 UTC
I've recently downloaded Repentogon whilst already using Stats+ and I seem to have found an error with the bag of crafting external item description display, where the items shown are not in fact the items produced by the bag. The three screenshots are what I believe the error is coming from. I'm sorry if this isn't helpful as I don't know too much about the code but hopefully everything can be fixed soon. :)
![Screenshot 2024-03-03 151840](https://github.com/aleksander-ciesielski/isaac-stats-plus/assets/161995827/fcb33c65-43df-47dd-80fc-d15e24eae4c5)
![Screenshot 2024-03-03 151854](https://github.com/aleksander-ciesielski/isaac-stats-plus/assets/161995827/6bd26718-01b8-4e22-b004-96c45383fc85)
![Screenshot 2024-03-03 151900](https://github.com/aleksander-ciesielski/isaac-stats-plus/assets/161995827/1e07baa5-c760-4b5b-ba9e-c13b8f5fa0c7)

**Comment by One656565** [comment] 2024-03-05 02:09
I have the same problem

**Comment by aleksander-ciesielski** [comment] 2024-03-12 21:21
duplicate of #8

**Comment by aleksander-ciesielski** [comment] 2024-03-13 16:48
actually I forgot that you mentioned something about the bag of crafting, sorry @LlamaLord23 - is it fixed for you after the update? I'm pretty sure there are no interactions between Stats+ and the bag of crafting

**Comment by aleksander-ciesielski** [comment] 2024-04-21 20:06
closing due to inactivity

**Closed by aleksander-ciesielski** 2024-04-21 20:06 UTC
